---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/mysql-router-community
  tag: "8.4.4"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
