apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-template
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: mysql-router
    edition: community
    version: {{ .Chart.AppVersion | quote }}
data:
  mysql-router: |
{{ .Files.Get "files/mysqlrouterTemplate.tpl" | indent 4 }}
