MINIO_ROOT_USER={{ getenv "MINIO_USER" }}
MINIO_ROOT_PASSWORD={{ AESCBCDecrypt (secretRead (getenv "SECRET_NAME") (getenv "NAMESPACE") (getenv "MINIO_USER")) }}
MINIO_CERT_DIR={{ getenv "CERT_MOUNT" }}
MINIO_ADDRESS=0.0.0.0:{{ getenv "MINIO_PORT" "9000" }}
MINIO_CONSOLE_ADDRESS=0.0.0.0:{{ getenv "CONSOLE_PORT" "9090" }}
