apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-template
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: etcd
    version: {{ .Chart.AppVersion | quote }}
data:
  etcd: |
{{ .Files.Get "files/etcdTemplate.tpl" | indent 4 }}
