apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-template
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: hugegraph
    version: {{ .Chart.AppVersion | quote }}
data:
  hugegraph: |
{{ .Files.Get "files/hugegraphTemplate.tpl" | indent 4 }}
