apiVersion: v2
name: hugegraph-hubble-1.3.0
description: HugeGraph Hubble 1.3.0 configuration and pod templates for UPM.
type: application
version: 1.0.0
appVersion: "1.3.0"
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.31.3
    tags:
      - bitnami-common
