---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/hugegraph-hubble
  tag: "1.3.0"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent-hugegraph-hubble
    tag: "v1.1.2"
    digest: ""
    pullPolicy: IfNotPresent
