---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/hugegraph-hubble
  tag: "1.3.0"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "1.3.0-hugegraph-hubble"
    digest: ""
    pullPolicy: IfNotPresent
