apiVersion: v2
appVersion: 7.17.14
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.31.3
name: kibana-7.17.14
version: 1.1.0
description: Kibana software packages, including configuration templates and pod templates.
type: application
keywords:
  - kibana
  - elasticsearch
  - observability
  - logging
  - monitoring
