---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/kibana
  tag: "7.17.14"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
