extends: default

ignore: |
  **/charts/templates/**

rules:
  line-length:
    max: 180
    level: warning
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
  document-start: disable
