---
defaults:
  i18n_locale: "en"
  encryption_key: "33f284458ea2078ffb14e985e789b3f2"
  monitoring_enabled: "true"
  monitoring_ui_container_apm_enabled: "true"
  monitoring_ui_container_elasticsearch_enabled: "true"
