listen_addresses = '*'
port = {{ getenv "POSTGRESQL_PORT"}}
max_connections = {{ getv "/postgresql/max_connections" }}
max_prepared_transactions = {{ getv "/postgresql/max_prepared_transactions" }}
checkpoint_timeout = 5min
max_wal_size = 1GB
min_wal_size = 80MB
wal_level = replica
max_wal_senders = 10
wal_log_hints = on
wal_keep_size = 512
wal_sender_timeout = 60s
track_commit_timestamp = on
hot_standby = on
max_standby_streaming_delay = 30s
wal_receiver_status_interval = 10s
hot_standby_feedback = on
wal_receiver_timeout = 60s
log_truncate_on_rotation = on
log_timezone = 'PRC'
timezone = 'PRC'
datestyle = 'iso, mdy'
default_text_search_config = 'pg_catalog.english'
dynamic_shared_memory_type = posix
shared_buffers = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 4 }}MB
effective_cache_size = {{ mul (div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 4) 3 }}MB
archive_mode = on
archive_command = 'cp  %p {{getenv "DATA_DIR"}}/archive/%f'
log_destination = 'stderr'
logging_collector = on
log_rotation_size = 1GB
data_directory = '{{getenv "DATA_DIR"}}'
log_directory = '{{getenv "LOG_MOUNT"}}'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_file_mode = 0600
log_rotation_age = 1d
hba_file = '{{getenv "DATA_DIR"}}/pg_hba.conf'
ident_file = '{{getenv "DATA_DIR"}}/pg_ident.conf'