listen_addresses = '*'
port = {{ getenv "POSTGRESQL_PORT" "5432" }}
max_prepared_transactions = {{ getv "/postgresql/max_prepared_transactions" }}
idle_in_transaction_session_timeout = {{ getv "/postgresql/idle_in_transaction_session_timeout" }}
statement_timeout = {{ getv "/postgresql/statement_timeout" }}
checkpoint_timeout = {{ getv "/postgresql/checkpoint_timeout" }}
checkpoint_completion_target = {{ getv "/postgresql/checkpoint_completion_target" }}
max_wal_size = {{ getv "/postgresql/max_wal_size" }}
min_wal_size = 80MB
wal_level = replica
max_wal_senders = 10
wal_log_hints = on
wal_sender_timeout = 120s
wal_receiver_timeout = 60s
wal_receiver_status_interval = 10s
max_parallel_workers = {{ atoi (getenv "PGSQL_CPU_LIMIT") }}
max_parallel_workers_per_gather = 1
{{- if le (atoi (getenv "PGSQL_MEMORY_LIMIT")) 2048 }}
max_connections = 100
shared_buffers = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 5 }}MB
work_mem = 4MB
maintenance_work_mem = 8MB
effective_cache_size = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 2 }}MB
wal_buffers = 4MB
huge_pages = off
{{- else if le (atoi (getenv "PGSQL_MEMORY_LIMIT")) 4096 }}
max_connections = 100
shared_buffers = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 4 }}MB
work_mem = 8MB
maintenance_work_mem = 16MB
effective_cache_size = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 2 }}MB
wal_buffers = 8MB
huge_pages = on
{{- else if le (atoi (getenv "PGSQL_MEMORY_LIMIT")) 8192 }}
max_connections = 100
shared_buffers = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 4 }}MB
work_mem = 16MB
maintenance_work_mem = 32MB
effective_cache_size = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 2 }}MB
wal_buffers = 16MB
huge_pages = on
{{- else if le (atoi (getenv "PGSQL_MEMORY_LIMIT")) 32768 }}
max_connections = 100
shared_buffers = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 3 }}MB
work_mem = 64MB
maintenance_work_mem = 128MB
effective_cache_size = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 2 }}MB
wal_buffers = 16MB
huge_pages = on
{{- else if le (atoi (getenv "PGSQL_MEMORY_LIMIT")) 65536 }}
max_connections = 100
shared_buffers = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 3 }}MB
work_mem = 128MB
maintenance_work_mem = 256MB
effective_cache_size = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 2 }}MB
wal_buffers = 16MB
huge_pages = on
{{- else }}
max_connections = 100
shared_buffers = 32GB
work_mem = 1GB
maintenance_work_mem = 2GB
effective_cache_size = {{ div (atoi (getenv "PGSQL_MEMORY_LIMIT")) 2 }}MB
wal_buffers = 16MB
huge_pages = on
{{- end }}
autovacuum_vacuum_scale_factor = {{ getv "/postgresql/autovacuum_vacuum_scale_factor" }}
autovacuum_analyze_scale_factor = {{ getv "/postgresql/autovacuum_analyze_scale_factor" }}
autovacuum_max_workers = {{ atoi (getenv "PGSQL_CPU_LIMIT") }}
random_page_cost = 2.0
effective_io_concurrency = 200
default_statistics_target = 100
track_commit_timestamp = on
hot_standby = on
max_standby_streaming_delay = 30s
hot_standby_feedback = on
log_truncate_on_rotation = on
log_timezone = 'PRC'
timezone = 'PRC'
datestyle = 'iso, mdy'
default_text_search_config = 'pg_catalog.english'
dynamic_shared_memory_type = posix
# archive_mode = off
# archive_command = ''
wal_keep_size = 10GB
log_min_duration_statement = {{ getv "/postgresql/log_min_duration_statement" }}
log_checkpoints = on
log_destination = 'stderr'
logging_collector = on
log_rotation_size = 1GB
data_directory = '{{ getenv "DATA_DIR" }}'
log_directory = '{{ getenv "LOG_MOUNT" }}'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_file_mode = 0600
log_rotation_age = 1d
track_io_timing = on
hba_file = '{{ getenv "CONF_DIR" }}/pg_hba.conf'
ident_file = '{{ getenv "DATA_DIR" }}/pg_ident.conf'
jit = {{ getv "/postgresql/jit" }}
