apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-parameters-detail
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: minio
    version: {{ .Chart.AppVersion | quote }}
data:
  minio: |
{{ .Files.Get "files/minioParametersDetail.json" | indent 4 }}
