---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/redis
  tag: "7.0.14"
  digest: ""
  pullPolicy: IfNotPresent

metrics:
  image:
    registry: quay.io
    repository: upmio/redis-exporter
    tag: "v1.76.0-alpine"
    digest: ""
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
