---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/kafka
  tag: "3.5.2"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
