apiVersion: v2
appVersion: 8.0.15
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.31.3
name: mongodb-8.0.15
version: 1.1.0
description: mongodb software packages, including configuration templates and pod templates.
type: application
keywords:
  - mongodb
  - database
  - nosql
  - document store
