---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/mongodb
  tag: "8.0.15"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
