---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/postgresql
  tag: "15.12"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/postgresql-agent
    tag: "15"
    pullPolicy: IfNotPresent
