apiVersion: v1
data:
  imageRegistry: "quay.io"
  imagePullSecret: ""
  template: |
    {
      "shared_env": [],
      "env": [
        {
          "name": "UNIT_SN",
          "valueFrom": {
            "fieldRef": {
              "apiVersion": "v1",
              "fieldPath": "metadata.labels['unit.sn']"
            }
          }
        },
        {
          "name": "SERVICE_NAME",
          "valueFrom": {
            "fieldRef": {
              "apiVersion": "v1",
              "fieldPath": "metadata.labels['upm.api/service.name']"
            }
          }
        },
        {
          "name": "NAMESPACE",
          "valueFrom": {
            "fieldRef": {
              "apiVersion": "v1",
              "fieldPath": "metadata.namespace"
            }
          }
        },
        {
          "name": "KAFKA_MEMORY_LIMIT",
          "valueFrom": {
            "resourceFieldRef": {
              "containerName": "kafka",
              "resource": "limits.memory",
              "divisor": "1Mi"
            }
          }
        },
        {
          "name": "DATA_DIR",
          "value": "$(DATA_MOUNT)/data"
        },
        {
          "name": "POD_NAME",
          "valueFrom": {
            "fieldRef": {
              "apiVersion": "v1",
              "fieldPath": "metadata.name"
            }
          }
        }
      ],
      "init_containers": [
        {
          "name": "init-container",
          "image": "upmio/kafka:3.5.2.1",
          "command": [
            "bash",
            "-c",
            "serverMGR.sh initialize"
          ],
          "security_context": {
            "privileged": true,
            "runAsUser": 0
          }
        }
      ],
      "main_container": {
        "name": "kafka",
        "image": "upmio/kafka:3.5.2.1",
        "liveness_probe": {
          "exec": {
            "command": [
              "bash",
              "-c",
              "</dev/tcp/localhost/9001"
            ]
          },
          "failureThreshold": 3,
          "initialDelaySeconds": 12,
          "periodSeconds": 12,
          "timeoutSeconds": 4
        },
        "readiness_probe": {
          "exec": {
            "command": [
              "bash",
              "-c",
              "unset JMX_PORT; kafka-broker-api-versions.sh --bootstrap-server=${POD_NAME}.${SERVICE_NAME}-headless-svc.${NAMESPACE}:${INTERNAL_PORT} > /dev/null"
            ]
          },
          "failureThreshold": 3,
          "initialDelaySeconds": 18,
          "periodSeconds": 18,
          "timeoutSeconds": 10
        },
        "startup_probe": {
          "exec": {
            "command": [
              "timeout",
              "3",
              "bash",
              "-c",
              "</dev/tcp/localhost/9001"
            ]
          },
          "failureThreshold": 3,
          "periodSeconds": 12,
          "timeoutSeconds": 4
        },
        "service_ports": [
          {
            "name": "internal",
            "protocol": "TCP",
            "port": 9092,
            "appProtocol": "TCP"
          },
          {
            "name": "kafka",
            "protocol": "TCP",
            "port": 9094,
            "appProtocol": "TCP"
          },
          {
            "name": "jmx",
            "protocol": "TCP",
            "port": 9999,
            "appProtocol": "http"
          }
        ]
      },
      "sidecars": [
        {
          "name": "unit-agent",
          "image": "upmio/unit-agent:v1.2.3",
          "service_ports": [
            {
              "name": "unit-agent",
              "protocol": "TCP",
              "port": 2214,
              "appProtocol": "TCP"
            }
          ],
          "resource": {
            "requests": {
              "memory": "128Mi",
              "cpu": "100m"
            }
          }
        }
      ],
      "annotations": {}
    }
kind: ConfigMap
metadata:
  labels:
    upm.io/owner: upm
  name: kafka-3.5.2.1-pod-tmpl
