#!/usr/bin/env bash

set -o nounset

# ##############################################################################
# Globals, settings
# ##############################################################################
POSIXLY_CORRECT=1
export POSIXLY_CORRECT
LANG=C

VERSION="v1.8.7.1"

# ##############################################################################
# common function package
# ##############################################################################
die() {
  local status="${1}"
  shift
  local function_name="${1}"
  shift
  error "${function_name}" "$*"
  exit "$status"
}

error() {
  local function_name="${1}"
  shift
  local timestamp
  timestamp="$(date +"%Y-%m-%d %T %N")"

  echo "[${timestamp}] ERR | (${VERSION})[${function_name}]: $* ;"
}

info() {
  local function_name="${1}"
  shift
  local timestamp
  timestamp="$(date +"%Y-%m-%d %T %N")"

  echo "[${timestamp}] INFO| (${VERSION})[${function_name}]: $* ;"
}

get_pwd() {
  local func_name="get_pwd"
  local user="${1}"

  [[ -v SECRET_MOUNT ]] || {
    error "${func_name}" "get env SECRET_MOUNT failed !"
    return 2
  }

  [[ -d ${SECRET_MOUNT} ]] || {
    error "${func_name}" "Not found ${SECRET_MOUNT} failed !"
    return 2
  }

  # echo -n "password" | od -A n -t x1 | tr -d ' '
  local enc_key="3765323063323065613735363432333161373664643833616331636637303133"
  local enc_iv="66382f4e654c734a2a732a7679675640"
  local enc_type="-aes-256-cbc"

  local secret_file="${SECRET_MOUNT}/${user}"
  [[ -f "${secret_file}" ]] || {
    error "${func_name}" "get file ${secret_file} failed !"
    return 2
  }

  local enc_base64
  enc_base64="$(cat "${secret_file}")" || {
    error "${func_name}" "get enc_base64 failed!"
    return 2
  }

  password=$(printf "%s\n" "${enc_base64}" | openssl enc -d "${enc_type}" -base64 -K "${enc_key}" -iv "${enc_iv}" 2>/dev/null) || {
    error "${func_name}" "openssl enc failed"
    return 2
  }

  echo "${password}"
}

# ##############################################################################
# postgresql action function
# action function can use function( die ) and exit
# ##############################################################################
postgresql_logical_full_backup_to_s3() {
  local func_name="postgresql_logical_full_backup_to_s3"

  local admin_password
  admin_password="$(get_pwd "${ADM_USER}")" || die 40 "${func_name}" "get ${ADM_USER} password failed!"

  info "${func_name}" "start execute logical backup to s3 !"

  grpcurl -plaintext -d '{"BackupFile":"'"${BACKUP_FILE}"'","Username":"'"${ADM_USER}"'","Password":"'"${admin_password}"'","LogicalBackupMode":0,"S3Storage":{"Endpoint":"'"${S3_ENDPOINT}"'","Bucket":"'"${BUCKET}"'","AccessKey":"'"${S3_ACCESS_KEY}"'","SecretKey":"'"${S3_SECRET_KEY}"'"}}' "${DEST_HOST}":2214 postgresql.PostgresqlOperation.LogicalBackup || {
    die 41 "${func_name}" "execute logical backup to s3 failed!"
  }

  info "${func_name}" "execute logical backup to s3 done !"
}

postgresql_physical_full_backup_to_s3() {
  local func_name="postgresql_physical_full_backup_to_s3"

  local repl_password
  repl_password="$(get_pwd "${REPL_USER}")" || die 40 "${func_name}" "get ${REPL_USER} password failed!"

  info "${func_name}" "start execute physical backup to s3 !"

  grpcurl -plaintext -d '{"BackupFile":"'"${BACKUP_FILE}"'","Username":"'"${REPL_USER}"'","Password":"'"${repl_password}"'","S3Storage":{"Endpoint":"'"${S3_ENDPOINT}"'","Bucket":"'"${BUCKET}"'","AccessKey":"'"${S3_ACCESS_KEY}"'","SecretKey":"'"${S3_SECRET_KEY}"'"}}' "${DEST_HOST}":2214 postgresql.PostgresqlOperation.PhysicalBackup || {
    die 41 "${func_name}" "execute physical backup to s3 failed!"
  }

  info "${func_name}" "execute physical backup to s3 done !"
}

postgresql_physical_full_restore_from_s3() {
  local func_name="postgresql_physical_full_restore_from_s3"

  info "${func_name}" "start execute physical restore from s3 !"

  grpcurl -plaintext -d '{"BackupFile":"'"${BACKUP_FILE}"'","S3Storage":{"Endpoint":"'"${S3_ENDPOINT}"'","Bucket":"'"${BUCKET}"'","AccessKey":"'"${S3_ACCESS_KEY}"'","SecretKey":"'"${S3_SECRET_KEY}"'"}}' "${DEST_HOST}":2214 postgresql.PostgresqlOperation.Restore || {
    die 41 "${func_name}" "execute physical restore from s3 failed!"
  }

  info "${func_name}" "execute physical restore from s3 done !"
}

# ##############################################################################
# mysql action function
# action function can use function( die ) and exit
# ##############################################################################
mysql_logical_full_backup_to_s3() {
  local func_name="mysql_logical_full_backup_to_s3"

  local admin_password
  admin_password="$(get_pwd "${ADM_USER}")" || die 40 "${func_name}" "get ${ADM_USER} password failed!"

  info "${func_name}" "start execute logical backup to s3 !"

  grpcurl -plaintext -d '{"BackupFile":"'"${BACKUP_FILE}"'","ConfFile":"'"${CONF_FILE}"'","SocketFile":"'"${SOCKET_FILE}"'","Username":"'"${ADM_USER}"'","Password":"'"${admin_password}"'","LogicalBackupMode":0,"S3Storage":{"Endpoint":"'"${S3_ENDPOINT}"'","Bucket":"'"${BUCKET}"'","AccessKey":"'"${S3_ACCESS_KEY}"'","SecretKey":"'"${S3_SECRET_KEY}"'"}}' "${DEST_HOST}":2214 mysql.MysqlOperation.LogicalBackup || {
    die 41 "${func_name}" "execute logical backup to s3 failed!"
  }

  info "${func_name}" "execute logical backup to s3 done !"

}

mysql_physical_full_backup_to_s3() {
  local func_name="mysql_physical_full_backup_to_s3"

  local admin_password
  admin_password="$(get_pwd "${ADM_USER}")" || die 40 "${func_name}" "get ${ADM_USER} password failed!"

  info "${func_name}" "start execute physical backup to s3 !"

  grpcurl -plaintext -d '{"BackupFile":"'"${BACKUP_FILE}"'","ConfFile":"'"${CONF_FILE}"'","SocketFile":"'"${SOCKET_FILE}"'","Username":"'"${ADM_USER}"'","Password":"'"${admin_password}"'","Parallel":10,"PhysicalBackupTool":0,"S3Storage":{"Endpoint":"'"${S3_ENDPOINT}"'","Bucket":"'"${BUCKET}"'","AccessKey":"'"${S3_ACCESS_KEY}"'","SecretKey":"'"${S3_SECRET_KEY}"'"}}' "${DEST_HOST}":2214 mysql.MysqlOperation.PhysicalBackup || {
    die 41 "${func_name}" "execute physical backup to s3 failed!"
  }

  info "${func_name}" "execute physical backup to s3 done !"

}

mysql_physical_full_restore_from_s3() {
  local func_name="mysql_physical_full_restore_from_s3"

  info "${func_name}" "start execute physical restore from s3 !"

  grpcurl -plaintext -d '{"BackupFile":"'"${BACKUP_FILE}"'","Parallel":10,"S3Storage":{"Endpoint":"'"${S3_ENDPOINT}"'","Bucket":"'"${BUCKET}"'","AccessKey":"'"${S3_ACCESS_KEY}"'","SecretKey":"'"${S3_SECRET_KEY}"'"}}' "${DEST_HOST}":2214 mysql.MysqlOperation.Restore || {
    die 41 "${func_name}" "execute physical restore from s3 failed!"
  }

  info "${func_name}" "execute physical restore from s3 done !"
}

mysql_clone() {
  local func_name="mysql_clone"

  local replication_password
  replication_password="$(get_pwd "${REPL_USER}")" || die 40 "${func_name}" "get ${REPL_USER} password failed!"

  local admin_password
  admin_password="$(get_pwd "${ADM_USER}")" || die 40 "${func_name}" "get ${ADM_USER} password failed!"

  info "${func_name}" "start execute mysql clone !"

  grpcurl -plaintext -d '{"SourceCloneUser":"'"${REPL_USER}"'","SourceClonePassword":"'"${replication_password}"'","SourceHost":"'"${SOURCE_HOST}"'","SourcePort":'"${SOURCE_PORT}"',"SocketFile":"'"${SOCKET_FILE}"'","Username":"'"${ADM_USER}"'","Password":"'"${admin_password}"'"}' "${DEST_HOST}":2214 mysql.MysqlOperation.Clone || {
    die 41 "${func_name}" "execute mysql clone failed !"
  }

  info "${func_name}" "execute mysql clone done !"

}

mysql_gtid_purged() {
  local func_name="mysql_gtid_purged"

  local admin_password
  admin_password="$(get_pwd "${ADM_USER}")" || die 40 "${func_name}" "get ${ADM_USER} password failed!"

  info "${func_name}" "start execute mysql gtid-purged !"

  case "${ARCH_MODE}" in
  "replication")
    grpcurl -plaintext -d '{"SocketFile":"'"${SOCKET_FILE}"'","Username":"'"${ADM_USER}"'","Password":"'"${admin_password}"'","ArchMode":0}' "${DEST_HOST}":2214 mysql.MysqlOperation.GtidPurge || {
      die 40 "${func_name}" "execute replication mode gtid purge failed"
    }
    ;;
  "group_replication")
    grpcurl -plaintext -d '{"SocketFile":"'"${SOCKET_FILE}"'","Username":"'"${ADM_USER}"'","Password":"'"${admin_password}"'","ArchMode":1}' "${DEST_HOST}":2214 mysql.MysqlOperation.GtidPurge || {
      die 40 "${func_name}" "execute group_replication mode gtid purge failed"
    }
    ;;
  *)
    die 41 "${func_name}" "ARCH MODE ${ARCH_MODE} not support"
    ;;
  esac

  info "${func_name}" "run ${func_name} done."
}
# ##############################################################################
# The main() function is called at the action function.
# ##############################################################################
main() {
  local func_name="main"

  # get parameters
  local type="${1}"
  shift
  local action="${1}"
  shift

  case "${type}" in
  "postgresql")
    case "${action}" in
    "backup")
      [[ -v ADM_USER ]] || die 10 "Globals" "get env ADM_USER failed !"
      [[ -v REPL_USER ]] || die 10 "Globals" "get env REPL_USER failed !"
      [[ -v BACKUP_TYPE ]] || die 10 "Globals" "get env BACKUP_TYPE failed !"
      [[ -v BACKUP_FILE ]] || die 10 "Globals" "get env BACKUP_FILE failed !"

      [[ -v BUCKET ]] || die 10 "Globals" "get env BUCKET failed !"
      [[ -v S3_ENDPOINT ]] || die 10 "Globals" "get env S3_ENDPOINT failed !"
      [[ -v S3_ACCESS_KEY ]] || die 10 "Globals" "get env S3_ACCESS_KEY failed !"
      [[ -v S3_SECRET_KEY ]] || die 10 "Globals" "get env S3_SECRET_KEY failed !"

      case "${BACKUP_TYPE}" in
      "logical")
        postgresql_logical_full_backup_to_s3
        ;;
      "physical")
        postgresql_physical_full_backup_to_s3
        ;;
      esac
      ;;
    "restore")
      [[ -v BACKUP_FILE ]] || die 10 "Globals" "get env BACKUP_FILE failed !"

      [[ -v BUCKET ]] || die 10 "Globals" "get env BUCKET failed !"
      [[ -v S3_ENDPOINT ]] || die 10 "Globals" "get env S3_ENDPOINT failed !"
      [[ -v S3_ACCESS_KEY ]] || die 10 "Globals" "get env S3_ACCESS_KEY failed !"
      [[ -v S3_SECRET_KEY ]] || die 10 "Globals" "get env S3_SECRET_KEY failed !"

      physical_full_restore_from_s3
      ;;
    *)
      echo "Error: Unsupported action '${action}' for type 'postgresql'."
      die 5 "Supported actions: backup, restore"
      ;;
    esac
    ;;
  "mysql")
    case "$action" in
    "backup")
      [[ -v ADM_USER ]] || die 10 "Globals" "get env ADM_USER failed !"
      [[ -v CONF_FILE ]] || die 10 "Globals" "get env CONF_FILE failed !"
      [[ -v SOCKET_FILE ]] || die 10 "Globals" "get env SOCKET_FILE failed !"
      [[ -v BACKUP_TYPE ]] || die 10 "Globals" "get env BACKUP_TYPE failed !"
      [[ -v BACKUP_FILE ]] || die 10 "Globals" "get env BACKUP_FILE failed !"

      [[ -v BUCKET ]] || die 10 "Globals" "get env BUCKET failed !"
      [[ -v S3_ENDPOINT ]] || die 10 "Globals" "get env S3_ENDPOINT failed !"
      [[ -v S3_ACCESS_KEY ]] || die 10 "Globals" "get env S3_ACCESS_KEY failed !"
      [[ -v S3_SECRET_KEY ]] || die 10 "Globals" "get env S3_SECRET_KEY failed !"

      case "${BACKUP_TYPE}" in
      "logical")
        mysql_logical_full_backup_to_s3
        ;;
      "physical")
        mysql_physical_full_backup_to_s3
        ;;
      esac
      ;;
    "clone")
      [[ -v SOURCE_HOST ]] || die 10 "Globals" "get env SOURCE_HOST failed !"
      [[ -v SOURCE_PORT ]] || die 10 "Globals" "get env SOURCE_PORT failed !"
      [[ -v ADM_USER ]] || die 10 "Globals" "get env ADM_USER failed !"
      [[ -v REPL_USER ]] || die 10 "Globals" "get env REPL_USER failed !"
      [[ -v SOCKET_FILE ]] || die 10 "Globals" "get env SOCKET_FILE failed !"

      mysql_clone
      ;;
    "restore")
      [[ -v BACKUP_FILE ]] || die 10 "Globals" "get env BACKUP_FILE failed !"

      [[ -v BUCKET ]] || die 10 "Globals" "get env BUCKET failed !"
      [[ -v S3_ENDPOINT ]] || die 10 "Globals" "get env S3_ENDPOINT failed !"
      [[ -v S3_ACCESS_KEY ]] || die 10 "Globals" "get env S3_ACCESS_KEY failed !"
      [[ -v S3_SECRET_KEY ]] || die 10 "Globals" "get env S3_SECRET_KEY failed !"

      mysql_physical_full_restore_from_s3
      ;;
    "gtid-purged")
      [[ -v ADM_USER ]] || die 10 "Globals" "get env ADM_USER failed !"
      [[ -v SOCKET_FILE ]] || die 10 "Globals" "get env SOCKET_FILE failed !"
      [[ -v ARCH_MODE ]] || die 10 "Globals" "get env ARCH_MODE failed !"

      mysql_gtid_purged
      ;;
    *)
      echo "Error: Unsupported action '${action}' for type 'mysql'."
      die 5 "Supported actions: backup, restore, gtid-purged, clone"
      ;;
    esac
    ;;
  *)
    echo "Error: Unsupported type '${type}'."
    die 5 "Supported types: postgresql, mysql"
    ;;
  esac
}

[[ -v SECRET_MOUNT ]] || die 10 "Globals" "get env SECRET_MOUNT failed !"
[[ -d ${SECRET_MOUNT} ]] || die 11 "Globals" "Not found ${SECRET_MOUNT} !"
[[ -v DEST_HOST ]] || die 10 "Globals" "get env DEST_HOST failed !"

main "${@:-""}"
