apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-value
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: kibana
    version: {{ .Chart.AppVersion | quote }}
data:
  kibana: |
{{ .Files.Get "files/kibanaValue.yaml" | indent 4 }}
