apiVersion: v1
kind: PodTemplate
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: kibana
    version: {{ .Chart.AppVersion | quote }}
template:
  metadata:
    annotations:
      kubectl.kubernetes.io/default-container: kibana
    labels:
      type: kibana
      version: {{ .Chart.AppVersion | quote }}
  spec:
    tolerations:
      - key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
    dnsPolicy: ClusterFirst
    restartPolicy: Always
    terminationGracePeriodSeconds: 30
    securityContext:
      fsGroup: 1001
      fsGroupChangePolicy: OnRootMismatch
    initContainers:
      - name: init-container
        image: {{ include "kibana.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
        command:
          - "bash"
          - "-c"
          - "service-ctl.sh initialize"
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.name"
          - name: KBN_MEMORY_LIMIT
            valueFrom:
              resourceFieldRef:
                containerName: kibana
                resource: limits.memory
                divisor: "1Mi"
          - name: DATA_DIR
            value: "$(DATA_MOUNT)/data"
          - name: KBN_PATH_CONF
            value: "$(DATA_MOUNT)/conf"
          - name: KIBANA_PORT
            value: "5601"
          - name: AES_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AES_SECRET_KEY
                name: aes-secret-key
      - name: sysctl
        image: {{ include "kibana.image" . }}
        command:
          - "sysctl"
          - "-w"
          - "vm.max_map_count=262144"
        securityContext:
          privileged: true
          runAsUser: 0
    containers:
      - name: kibana
        image: {{ include "kibana.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 5601
            name: kibana
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.name"
          - name: DATA_DIR
            value: "$(DATA_MOUNT)/data"
          - name: KBN_PATH_CONF
            value: "$(DATA_MOUNT)/conf"
          - name: KIBANA_PORT
            value: "5601"
          - name: AES_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AES_SECRET_KEY
                name: aes-secret-key
        livenessProbe:
          exec:
            command:
              - "timeout"
              - "3"
              - "bash"
              - "-c"
              - "</dev/tcp/localhost/9001"
          failureThreshold: 3
          initialDelaySeconds: 12
          periodSeconds: 12
          timeoutSeconds: 4
          successThreshold: 1
        readinessProbe:
          exec:
            command:
              - "timeout"
              - "3"
              - "bash"
              - "-c"
              - "service-ctl.sh health"
          failureThreshold: 3
          initialDelaySeconds: 12
          periodSeconds: 30
          timeoutSeconds: 4
          successThreshold: 1
        startupProbe:
          exec:
            command:
              - "timeout"
              - "3"
              - "bash"
              - "-c"
              - "</dev/tcp/localhost/9001"
          failureThreshold: 3
          initialDelaySeconds: 12
          periodSeconds: 12
          timeoutSeconds: 4
          successThreshold: 1
      - name: unit-agent
        image: {{ include "kibana.agent.image" . }}
        imagePullPolicy: {{ .Values.agent.image.pullPolicy | quote }}
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 2214
            name: unit-agent
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.name"
          - name: UNIT_TYPE
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['kubectl.kubernetes.io/default-container']"
          - name: DATA_DIR
            value: "$(DATA_MOUNT)/data"
          - name: CONF_DIR
            value: "$(DATA_MOUNT)/conf"
          - name: CONFIG_PATH
            value: "$(DATA_MOUNT)/conf/kibana.yml"
          - name: KIBANA_PORT
            value: "5601"
          - name: MASTER_MEMBER_LIST
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.annotations['upm.api/master-member-list']"
          - name: AES_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: AES_SECRET_KEY
                name: aes-secret-key
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: "v1"
                fieldPath: "metadata.namespace"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
