---
global:
  imageRegistry: ""

image:
  registry: harbor.bsgchina.com
  repository: upmio/zookeeper
  tag: "3.8.4-upm-metrics-20260903"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
