---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/clickhouse
  tag: "25.8.29.51"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/clickhouse-agent
    tag: "25.8"
    pullPolicy: Always
