apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-parameters-detail
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: mysql
    edition: community
    version: {{ .Chart.AppVersion | quote }}
data:
  mysql: |
{{ .Files.Get "files/mysqlParametersDetail.json" | indent 4 }}
