apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-template
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: redis-sentinel
    version: {{ .Chart.AppVersion | quote }}
data:
  redis-sentinel: |
{{ .Files.Get "files/redissentinelTemplate.tpl" | indent 4 }}
