---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/postgresql
  tag: "15.13"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/postgresql-agent
    tag: "15"
    pullPolicy: IfNotPresent

metrics:
  image:
    registry: quay.io
    repository: prometheuscommunity/postgres-exporter
    tag: "v0.16.0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  user: "monitor"
  database: "postgres"
