apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-parameters-detail
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: proxysql
    version: {{ .Chart.AppVersion | quote }}
data:
  proxysql: |
{{ .Files.Get "files/proxysqlParametersDetail.json" | indent 4 }}
