---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/clickhouse-keeper
  tag: "25.8.29.51"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
