---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/clickhouse
  tag: "21.8.15.7"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/clickhouse-agent
    tag: "21.8"
    pullPolicy: IfNotPresent
