apiVersion: v2
appVersion: 1.23.1
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.31.3
name: pgbouncer-1.23.1
version: 1.1.0
description: PGBouncer software packages, including configuration templates and pod templates.
type: application
keywords:
  - postgresql
  - pgbouncer
  - database
  - sql
