apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-parameters-detail
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: mysql-router
    edition: community
    version: {{ .Chart.AppVersion }}
data:
  mysql-router: |
{{ .Files.Get "files/routerParametersDetail.json" | indent 4 }}
