apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-template
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: clickhouse-keeper
    version: {{ .Chart.AppVersion | quote }}
data:
  clickhouse-keeper: |
{{ .Files.Get "files/clickhouseKeeperTemplate.tpl" | indent 4 }}
