---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/milvus
  tag: "2.6.2"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "v1.1.0"
    pullPolicy: IfNotPresent
