global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/mysql-community
  tag: 8.0.35
  digest: ""
  pullPolicy: IfNotPresent

metrics:
  image:
    registry: quay.io
    repository: upmio/mysqld-exporter
    tag: 0.16.0
    digest: ""
    pullPolicy: IfNotPresent
    ## Mysqld Prometheus exporter resource requests and limits
    ## ref: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
    ## We usually recommend not to specify default resources and to leave this as a conscious
    ## choice for the user. This also increases chances charts run on environments with little
    ## resources, such as Minikube. If you do want to specify resources, uncomment the following
    ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    ## @param metrics.resourcesPreset Set container resources according to one common preset (allowed values: none, nano, micro, small, medium, large, xlarge, 2xlarge). This is ignored if metrics.resources is set (metrics.resources is recommended for production).
    ## More information: https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L15
    ##
    resourcesPreset: "nano"
    ## @param metrics.resources Set container requests and limits for different resources like CPU or memory (essential for production workloads)
    ## Example:
    ## resources:
    ##   requests:
    ##     cpu: 200m
    ##     memory: 256Mi
    ##   limits:
    ##     cpu: 500m
    ##     memory: 512Mi
    ##
    resources: {}
agent:
  image:
    registry: quay.io
    repository: upmio/mysql-agent-community
    tag: 8.0
    pullPolicy: IfNotPresent