apiVersion: v1
data:
  imageRegistry: "quay.io"
  imagePullSecret: ""
  template: |
    {
      "shared_env": [],
      "env": [
        {
          "name": "SERVICE_GROUP_NAME",
          "valueFrom": {
            "fieldRef": {
              "apiVersion": "v1",
              "fieldPath": "metadata.labels['upm.api/service-group.name']"
            }
          }
        },
        {
          "name": "POD_NAME",
          "valueFrom": {
            "fieldRef": {
              "apiVersion": "v1",
              "fieldPath": "metadata.name"
            }
          }
        },
        {
          "name": "NAMESPACE",
          "valueFrom": {
            "fieldRef": {
              "apiVersion": "v1",
              "fieldPath": "metadata.namespace"
            }
          }
        },
        {
          "name": "DATA_DIR",
          "value": "$(DATA_MOUNT)/data"
        }
      ],
      "init_containers": [
        {
          "name": "init-container",
          "image": "upmio/elasticsearch:7.17.14.1",
          "command": [
            "bash",
            "-c",
            "serverMGR.sh initialize"
          ]
        },
        {
          "name": "sysctl",
          "image": "upmio/elasticsearch:7.17.14.1",
          "command": [
            "bash",
            "-c",
            "sysctl -w vm.max_map_count=262144"
          ],
          "security_context": {
            "privileged": true,
            "runAsUser": 0
          }
        }
      ],
      "main_container": {
        "name": "elasticsearch",
        "image": "upmio/elasticsearch:7.17.14.1",
        "liveness_probe": {
          "exec": {
            "command": [
              "timeout",
              "3",
              "bash",
              "-c",
              "</dev/tcp/localhost/9001"
            ]
          },
          "failureThreshold": 3,
          "initialDelaySeconds": 12,
          "periodSeconds": 12,
          "timeoutSeconds": 4
        },
        "readiness_probe": {
          "exec": {
            "command": [
              "timeout",
              "3",
              "bash",
              "-c",
              "serverMGR.sh status"
            ]
          },
          "failureThreshold": 3,
          "initialDelaySeconds": 12,
          "periodSeconds": 12,
          "timeoutSeconds": 4
        },
        "startup_probe": {
          "exec": {
            "command": [
              "timeout",
              "3",
              "bash",
              "-c",
              "</dev/tcp/localhost/9001"
            ]
          },
          "failureThreshold": 3,
          "periodSeconds": 12,
          "timeoutSeconds": 4
        },
        "service_ports": [
          {
            "name": "elasticsearch",
            "protocol": "TCP",
            "port": 9200,
            "appProtocol": "TCP"
          },
          {
            "name": "transport",
            "protocol": "TCP",
            "port": 9300,
            "appProtocol": "TCP"
          },
          {
            "name": "exporter",
            "protocol": "TCP",
            "port": 9114,
            "appProtocol": "TCP"
          }
        ]
      },
      "sidecars": [
        {
          "name": "exporter",
          "image": "prometheuscommunity/elasticsearch-exporter:v1.6.0",
          "command": [
            "sh",
            "-c",
            "export ES_USERNAME=$(head -n 1 ${DATA_DIR}/kbn_user.txt) && export ES_PASSWORD=$(head -n 2 ${DATA_DIR}/kbn_user.txt | tail -n 1) && /bin/elasticsearch_exporter --es.all --es.indices --collector.clustersettings --collector.cluster-info --es.indices_settings --es.shards --es.snapshots --es.timeout=30s --es.ssl-skip-verify --es.uri=https://${POD_NAME}:${ELASTICSEARCH_PORT} --web.listen-address=:${EXPORTER_PORT} --web.telemetry-path=/metrics"
          ]
        },
        {
          "name": "unit-agent",
          "image": "upmio/unit-agent:v1.2.3",
          "service_ports": [
            {
              "name": "unit-agent",
              "protocol": "TCP",
              "port": 2214,
              "appProtocol": "TCP"
            }
          ],
          "resource": {
            "requests": {
              "memory": "128Mi",
              "cpu": "100m"
            }
          }
        }
      ],
      "annotations": {
        "upm.unit.metrics": "[\"elasticsearch_cluster_health_up\",\"elasticsearch_node_stats_up\"]"
      }
    }
kind: ConfigMap
metadata:
  labels:
    upm.io/owner: upm
  name: elasticsearch-7.17.14.1-pod-tmpl
