---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/redis-sentinel
  tag: "7.0.14"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/agent
    tag: "v1.0.0"
    pullPolicy: IfNotPresent
