apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "Chart.Name" . }}-parameters-detail
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    upm.io/owner: upm
    type: mysql
    edition: community
    version: {{ .Values.appVersion }}
data:
  mysql: |
    {{ .Files.Get "files/mysqlParametersDetail.json" | indent 4 }}
