apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-template
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: elasticsearch
    version: {{ .Chart.AppVersion | quote }}
data:
  elasticsearch: |
{{ .Files.Get "files/elasticsearchTemplate.tpl" | indent 4 }}
