---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/hugegraph
  tag: "1.3.0"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/unit-agent
    tag: "v1.1.1"
    digest: ""
    pullPolicy: IfNotPresent
