apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-template
  namespace: {{ .Release.Namespace | quote }}
  labels:
    upm.io/owner: upm
    type: hugegraph-hubble
    version: {{ .Chart.AppVersion | quote }}
data:
  hugegraph-hubble: |
{{ .Files.Get "files/hugegraphHubbleTemplate.tpl" | indent 4 }}
