[inet_http_server]
port=127.0.0.1:9001

[supervisorctl]
serverurl=http://127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisord]
logfile=%(ENV_LOG_MOUNT)s/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=%(ENV_DATA_MOUNT)s/supervisord.pid
nodaemon=true
minfds=1024
minprocs=200
user=hugegraph
childlogdir=/tmp

[program:unit_app]
command=/usr/local/bin/service-ctl.sh start
stderr_logfile=%(ENV_LOG_MOUNT)s/unit_app.err.log
stdout_logfile=%(ENV_LOG_MOUNT)s/unit_app.out.log
user=hugegraph
startsecs=5
stopwaitsecs=30
stopsignal=TERM
autostart=false
autorestart=false
startretries=3
