---
global:
  imageRegistry: ""

image:
  registry: quay.io
  repository: upmio/clickhouse
  tag: "23.8.16.40"
  digest: ""
  pullPolicy: IfNotPresent

agent:
  image:
    registry: quay.io
    repository: upmio/clickhouse-agent
    tag: "23.8"
    pullPolicy: Always
