name: Security Nightly

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy (filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Resolve base/head refs for default branch
        id: revs
        shell: bash
        run: |
          set -euo pipefail
          DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
          git fetch origin "${DEFAULT_BRANCH}" --depth=2
          HEAD_SHA=$(git rev-parse "origin/${DEFAULT_BRANCH}")
          # Fallback to HEAD when there is no parent (single-commit branch)
          BASE_SHA=$(git rev-parse "${HEAD_SHA}^" 2>/dev/null || echo "${HEAD_SHA}")
          echo "head_sha=${HEAD_SHA}" >> "$GITHUB_OUTPUT"
          echo "base_sha=${BASE_SHA}" >> "$GITHUB_OUTPUT"
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ steps.revs.outputs.base_sha }}
          head-ref: ${{ steps.revs.outputs.head_sha }}

  summarize:
    runs-on: ubuntu-latest
    needs: [trivy-scan, dependency-review]
    steps:
      - name: Summary
        run: |
          echo "### Nightly Security Scan" >> $GITHUB_STEP_SUMMARY
          echo "- Trivy: ${{ needs.trivy-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Dependency Review: ${{ needs.dependency-review.result }}" >> $GITHUB_STEP_SUMMARY
